name: Fetch CMS Data and Upload Artifact

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Adjust this to your project's Node version

      - name: Install dependencies
        run: npm ci

      - name: Run CMS task
        run: npm run cms
        env:
          # Add any environment variables your CMS task needs
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-data
          path: static/data/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update JSON files
        run: |
          rm -rf gh-pages/static/data
          cp -R static/data gh-pages/static/

      - name: Commit and push if changed
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update content files" && git push)
